"""
ProxyWhirl: Advanced Python Proxy Rotation Library

A production-ready library for intelligent proxy rotation with auto-fetching,
validation, and persistence capabilities.
"""

from proxywhirl.browser import BrowserRenderer
from proxywhirl.cache import CacheManager
from proxywhirl.cache_models import (
    CacheConfig,
    CacheEntry,
    CacheStatistics,
    CacheTierConfig,
    HealthStatus as CacheHealthStatus,
    TierStatistics,
)
from proxywhirl.exceptions import (
    CacheCorruptionError,
    CacheStorageError,
    CacheValidationError,
    ProxyAuthenticationError,
    ProxyConnectionError,
    ProxyFetchError,
    ProxyPoolEmptyError,
    ProxyStorageError,
    ProxyValidationError,
    ProxyWhirlError,
)
from proxywhirl.fetchers import (
    CSVParser,
    HTMLTableParser,
    JSONParser,
    PlainTextParser,
    ProxyFetcher,
    ProxyValidator,
    deduplicate_proxies,
)
from proxywhirl.models import (
    HealthMonitor,
    HealthStatus,
    Proxy,
    ProxyConfiguration,
    ProxyCredentials,
    ProxyFormat,
    ProxyPool,
    ProxySource,
    ProxySourceConfig,
    RenderMode,
    SourceStats,
    ValidationLevel,
)
from proxywhirl.rotator import ProxyRotator
from proxywhirl.sources import (
    ALL_HTTP_SOURCES,
    ALL_SOCKS4_SOURCES,
    ALL_SOCKS5_SOURCES,
    ALL_SOURCES,
    API_SOURCES,
    FREE_PROXY_LIST,
    GEONODE_HTTP,
    GEONODE_SOCKS4,
    GEONODE_SOCKS5,
    GITHUB_CLARKETM_HTTP,
    GITHUB_HOOKZOF_HTTP,
    GITHUB_MONOSANS_HTTP,
    GITHUB_MONOSANS_SOCKS4,
    GITHUB_MONOSANS_SOCKS5,
    GITHUB_THESPECBAY_HTTP,
    GITHUB_THESPECBAY_SOCKS4,
    GITHUB_THESPECBAY_SOCKS5,
    PROXY_NOVA,
    PROXY_SCRAPE_HTTP,
    PROXY_SCRAPE_SOCKS4,
    PROXY_SCRAPE_SOCKS5,
    RECOMMENDED_SOURCES,
)
from proxywhirl.strategies import (
    CompositeStrategy,
    GeoTargetedStrategy,
    LeastUsedStrategy,
    PerformanceBasedStrategy,
    RandomStrategy,
    RotationStrategy,
    RoundRobinStrategy,
    SessionPersistenceStrategy,
    StrategyRegistry,
    WeightedStrategy,
)
from proxywhirl.logging_config import (
    LogConfiguration,
    LogHandlerConfig,
    LogHandlerType,
    LogLevel,
    create_default_console_handler,
    create_file_handler,
    create_http_handler,
    create_syslog_handler,
    load_logging_config,
)
from proxywhirl.logging_context import (
    LogContext,
    bind_context,
    clear_context,
    generate_request_id,
    get_context,
    get_operation,
    get_proxy_url,
    get_request_id,
    get_source,
    get_strategy,
    get_user_id,
    log_with_context,
    set_operation,
    set_proxy_url,
    set_request_id,
    set_source,
    set_strategy,
    set_user_id,
)
from proxywhirl.logging_handlers import (
    apply_logging_configuration,
    configure_file_handler_with_rotation,
    create_handler_sink,
    get_drop_counter,
    reload_logging_configuration,
    reset_drop_counter,
)
from proxywhirl.utils import (
    configure_logging,
    create_proxy_from_url,
    decrypt_credentials,
    encrypt_credentials,
    generate_encryption_key,
    is_valid_proxy_url,
    parse_proxy_url,
    proxy_to_dict,
    validate_proxy_model,
)

__version__ = "1.0.0"

__all__: list[str] = [
    # Version
    "__version__",
    # Cache Components
    "CacheManager",
    "CacheConfig",
    "CacheEntry",
    "CacheStatistics",
    "CacheTierConfig",
    "TierStatistics",
    "CacheHealthStatus",
    # Exceptions
    "ProxyWhirlError",
    "ProxyValidationError",
    "ProxyPoolEmptyError",
    "ProxyConnectionError",
    "ProxyAuthenticationError",
    "ProxyFetchError",
    "ProxyStorageError",
    "CacheCorruptionError",
    "CacheStorageError",
    "CacheValidationError",
    # Models
    "Proxy",
    "ProxyCredentials",
    "ProxyConfiguration",
    "ProxySourceConfig",
    "SourceStats",
    "ProxyPool",
    "HealthMonitor",
    # Enums
    "HealthStatus",
    "ProxySource",
    "ProxyFormat",
    "RenderMode",
    "ValidationLevel",
    # Core Classes
    "ProxyRotator",
    "ProxyFetcher",
    "ProxyValidator",
    "BrowserRenderer",
    # Protocols
    "RotationStrategy",
    # Strategy Registry
    "StrategyRegistry",
    # Strategies
    "CompositeStrategy",
    "RoundRobinStrategy",
    "RandomStrategy",
    "WeightedStrategy",
    "LeastUsedStrategy",
    "PerformanceBasedStrategy",
    "SessionPersistenceStrategy",
    "GeoTargetedStrategy",
    # Parsers
    "JSONParser",
    "CSVParser",
    "PlainTextParser",
    "HTMLTableParser",
    # Logging Configuration
    "LogConfiguration",
    "LogHandlerConfig",
    "LogHandlerType",
    "LogLevel",
    "load_logging_config",
    "create_default_console_handler",
    "create_file_handler",
    "create_http_handler",
    "create_syslog_handler",
    # Logging Handlers
    "apply_logging_configuration",
    "reload_logging_configuration",
    "create_handler_sink",
    "configure_file_handler_with_rotation",
    "get_drop_counter",
    "reset_drop_counter",
    # Logging Context
    "LogContext",
    "bind_context",
    "log_with_context",
    "get_context",
    "clear_context",
    "generate_request_id",
    "get_request_id",
    "set_request_id",
    "get_operation",
    "set_operation",
    "get_proxy_url",
    "set_proxy_url",
    "get_strategy",
    "set_strategy",
    "get_source",
    "set_source",
    "get_user_id",
    "set_user_id",
    # Utilities
    "configure_logging",
    "is_valid_proxy_url",
    "parse_proxy_url",
    "validate_proxy_model",
    "encrypt_credentials",
    "decrypt_credentials",
    "generate_encryption_key",
    "proxy_to_dict",
    "create_proxy_from_url",
    "deduplicate_proxies",
    # Built-in Proxy Sources (Individual)
    "FREE_PROXY_LIST",
    "PROXY_SCRAPE_HTTP",
    "PROXY_SCRAPE_SOCKS4",
    "PROXY_SCRAPE_SOCKS5",
    "GEONODE_HTTP",
    "GEONODE_SOCKS4",
    "GEONODE_SOCKS5",
    "PROXY_NOVA",
    "GITHUB_CLARKETM_HTTP",
    "GITHUB_THESPECBAY_HTTP",
    "GITHUB_THESPECBAY_SOCKS4",
    "GITHUB_THESPECBAY_SOCKS5",
    "GITHUB_MONOSANS_HTTP",
    "GITHUB_MONOSANS_SOCKS4",
    "GITHUB_MONOSANS_SOCKS5",
    "GITHUB_HOOKZOF_HTTP",
    # Built-in Proxy Sources (Collections)
    "ALL_HTTP_SOURCES",
    "ALL_SOCKS4_SOURCES",
    "ALL_SOCKS5_SOURCES",
    "ALL_SOURCES",
    "RECOMMENDED_SOURCES",
    "API_SOURCES",
]
