"""
ProxyWhirl: Advanced Python Proxy Rotation Library

A production-ready library for intelligent proxy rotation with auto-fetching,
validation, and persistence capabilities.
"""

from __future__ import annotations

from proxywhirl.browser import BrowserRenderer
from proxywhirl.cache import CacheManager
from proxywhirl.cache.models import (
    CacheConfig,
    CacheEntry,
    CacheStatistics,
    CacheTierConfig,
    TierStatistics,
)
from proxywhirl.cache.models import (
    HealthStatus as CacheHealthStatus,
)
from proxywhirl.circuit_breaker import AsyncCircuitBreaker, CircuitBreaker, CircuitBreakerState
from proxywhirl.config import DataStorageConfig
from proxywhirl.events import (
    Event,
    EventBus,
    EventHandler,
    EventSubscriber,
    EventType,
    get_event_bus,
    set_event_bus,
)
from proxywhirl.exceptions import (
    BrowserRenderError,
    CacheCorruptionError,
    CacheStorageError,
    CacheTierError,
    CacheValidationError,
    CircuitBreakerOpenError,
    EventLoopConflictError,
    GeoIPLookupError,
    MaxRetriesExhaustedError,
    ProxyAuthenticationError,
    ProxyConnectionContextError,
    ProxyConnectionError,
    ProxyFetchError,
    ProxyPoolEmptyError,
    ProxySourceUnavailableError,
    ProxyStorageError,
    ProxyValidationError,
    ProxyValidationPathError,
    ProxyWhirlError,
    RateLimitExceededError,
    RequestQueueFullError,
    SchemaMigrationError,
    StorageRecoveryError,
    TimeoutError,
)
from proxywhirl.fetchers import (
    CSVParser,
    HTMLTableParser,
    JSONParser,
    PlainTextParser,
    ProxyFetcher,
    ProxyValidator,
    deduplicate_proxies,
)
from proxywhirl.models import (
    BootstrapConfig,
    CircuitBreakerConfig,
    HealthMonitor,
    HealthStatus,
    Proxy,
    ProxyChain,
    ProxyConfiguration,
    ProxyCredentials,
    ProxyFormat,
    ProxyPool,
    ProxySource,
    ProxySourceConfig,
    RenderMode,
    SelectionContext,
    Session,
    SourceStats,
    StrategyConfig,
    ValidationLevel,
)
from proxywhirl.observability import (
    MetricsCollector,
    ObservabilityContext,
    Span,
    SpanContext,
    Tracer,
)
from proxywhirl.plugins import (
    HookPlugin,
    MiddlewarePlugin,
    ParserPlugin,
    PluginError,
    PluginInterface,
    PluginLoader,
    PluginRegistry,
    StrategyPlugin,
    get_plugin_registry,
    set_plugin_registry,
)
from proxywhirl.retry import (
    BackoffStrategy,
    CircuitBreakerEvent,
    HourlyAggregate,
    NonRetryableError,
    RetryableError,
    RetryAttempt,
    RetryExecutor,
    RetryMetrics,
    RetryOutcome,
    RetryPolicy,
)
from proxywhirl.rotator import AsyncProxyWhirl, ProxyWhirl
from proxywhirl.safe_regex import RegexComplexityError, RegexTimeoutError
from proxywhirl.sources import (
    ALL_HTTP_SOURCES,
    ALL_SOCKS4_SOURCES,
    ALL_SOCKS5_SOURCES,
    ALL_SOURCES,
    API_SOURCES,
    GEONODE_HTTP,
    GEONODE_SOCKS4,
    GEONODE_SOCKS5,
    GITHUB_KOMUTAN_HTTP,
    GITHUB_KOMUTAN_SOCKS4,
    GITHUB_KOMUTAN_SOCKS5,
    GITHUB_MONOSANS_HTTP,
    GITHUB_MONOSANS_SOCKS4,
    GITHUB_MONOSANS_SOCKS5,
    GITHUB_PROXIFLY_HTTP,
    GITHUB_PROXIFLY_SOCKS4,
    GITHUB_PROXIFLY_SOCKS5,
    GITHUB_THESPEEDX_HTTP,
    GITHUB_THESPEEDX_SOCKS4,
    GITHUB_THESPEEDX_SOCKS5,
    RECOMMENDED_SOURCES,
)
from proxywhirl.strategies import (
    CompositeStrategy,
    CostAwareStrategy,
    GeoTargetedStrategy,
    LeastUsedStrategy,
    PerformanceBasedStrategy,
    ProxyMetrics,
    RandomStrategy,
    RotationStrategy,
    RoundRobinStrategy,
    SessionPersistenceStrategy,
    StrategyRegistry,
    StrategyState,
    WeightedStrategy,
)
from proxywhirl.types import (
    AsyncHttpRequestCallback,
    CacheEvictionCallback,
    CacheFormat,
    ConfigAction,
    ErrorHandlerCallback,
    HealthCheckCallback,
    HttpRequestCallback,
    LoggingCallback,
    LogLevel,
    MCPMiddlewareCallback,
    MetricsCallback,
    PerformanceLevel,
    PoolAction,
    Protocol,
    ProxyAddCallback,
    ProxyProtocol,
    ProxyRemoveCallback,
    ProxySelectionCallback,
    ProxyType,
    ProxywhirlAction,
    RetryCallback,
    SessionCallback,
    SessionEvictionCallback,
)
from proxywhirl.types import (
    ValidationLevel as ValidationLevelType,
)
from proxywhirl.utils import (
    configure_logging,
    create_proxy_from_url,
    decrypt_credentials,
    encrypt_credentials,
    generate_encryption_key,
    is_valid_proxy_url,
    parse_proxy_url,
    proxy_to_dict,
    validate_proxy_model,
)
from proxywhirl.validators import (
    is_dead_status,
    is_degraded_status,
    is_health_status,
    is_healthy_proxy,
    is_healthy_proxy_list,
    is_healthy_status,
    is_non_negative,
    is_pool,
    is_positive,
    is_proxy,
    is_proxy_dict,
    is_proxy_list,
    is_session,
    is_success_rate,
    is_valid_host,
    is_valid_port,
    is_valid_proxy,
    is_working_proxy,
)
from proxywhirl.validators import (
    is_valid_proxy_url as is_valid_proxy_url_guard,
)

__version__ = "0.3.3"

__all__: list[str] = [
    # Version
    "__version__",
    # Configuration
    "BootstrapConfig",
    "DataStorageConfig",
    # Retry & Failover Components
    "RetryPolicy",
    "BackoffStrategy",
    "CircuitBreaker",
    "AsyncCircuitBreaker",
    "CircuitBreakerConfig",
    "CircuitBreakerState",
    "RetryExecutor",
    "RetryMetrics",
    "RetryAttempt",
    "RetryOutcome",
    "CircuitBreakerEvent",
    "HourlyAggregate",
    # Plugin System
    "PluginInterface",
    "PluginError",
    "StrategyPlugin",
    "ParserPlugin",
    "MiddlewarePlugin",
    "HookPlugin",
    "PluginRegistry",
    "PluginLoader",
    "get_plugin_registry",
    "set_plugin_registry",
    # Event System
    "Event",
    "EventBus",
    "EventType",
    "EventHandler",
    "EventSubscriber",
    "get_event_bus",
    "set_event_bus",
    # Observability
    "Tracer",
    "Span",
    "SpanContext",
    "MetricsCollector",
    "ObservabilityContext",
    # Cache Components
    "CacheManager",
    "CacheConfig",
    "CacheEntry",
    "CacheStatistics",
    "CacheTierConfig",
    "TierStatistics",
    "CacheHealthStatus",
    # Exceptions
    "ProxyWhirlError",
    "ProxyValidationError",
    "ProxyPoolEmptyError",
    "ProxyConnectionError",
    "ProxyAuthenticationError",
    "ProxyFetchError",
    "ProxyStorageError",
    "CacheCorruptionError",
    "CacheStorageError",
    "CacheValidationError",
    "RequestQueueFullError",
    "RateLimitExceededError",
    "MaxRetriesExhaustedError",
    "CircuitBreakerOpenError",
    "ProxyConnectionContextError",
    "CacheTierError",
    "ProxyValidationPathError",
    "GeoIPLookupError",
    "BrowserRenderError",
    "ProxySourceUnavailableError",
    "EventLoopConflictError",
    "SchemaMigrationError",
    "TimeoutError",
    "StorageRecoveryError",
    "RetryableError",
    "NonRetryableError",
    "RegexTimeoutError",
    "RegexComplexityError",
    # Models
    "Proxy",
    "ProxyChain",
    "ProxyCredentials",
    "ProxyConfiguration",
    "ProxySourceConfig",
    "SelectionContext",
    "Session",
    "SourceStats",
    "StrategyConfig",
    "ProxyPool",
    "HealthMonitor",
    # Enums
    "HealthStatus",
    "ProxySource",
    "ProxyFormat",
    "RenderMode",
    "ValidationLevel",
    # Core Classes
    "ProxyWhirl",
    "AsyncProxyWhirl",
    "ProxyFetcher",
    "ProxyValidator",
    "BrowserRenderer",
    # Protocols
    "RotationStrategy",
    # Strategy Registry
    "StrategyRegistry",
    # Strategy State Management
    "StrategyState",
    "ProxyMetrics",
    # Strategies
    "CompositeStrategy",
    "CostAwareStrategy",
    "RoundRobinStrategy",
    "RandomStrategy",
    "WeightedStrategy",
    "LeastUsedStrategy",
    "PerformanceBasedStrategy",
    "SessionPersistenceStrategy",
    "GeoTargetedStrategy",
    # Parsers
    "JSONParser",
    "CSVParser",
    "PlainTextParser",
    "HTMLTableParser",
    # Utilities
    "configure_logging",
    "is_valid_proxy_url",
    "parse_proxy_url",
    "validate_proxy_model",
    "encrypt_credentials",
    "decrypt_credentials",
    "generate_encryption_key",
    "proxy_to_dict",
    "create_proxy_from_url",
    "deduplicate_proxies",
    # TypeGuard Validators
    "is_valid_proxy",
    "is_healthy_proxy",
    "is_working_proxy",
    "is_pool",
    "is_session",
    "is_valid_proxy_url_guard",
    "is_valid_host",
    "is_valid_port",
    "is_valid_proxy",
    "is_health_status",
    "is_healthy_status",
    "is_degraded_status",
    "is_dead_status",
    "is_proxy",
    "is_proxy_list",
    "is_healthy_proxy_list",
    "is_proxy_dict",
    "is_success_rate",
    "is_non_negative",
    "is_positive",
    # Type Aliases (String Literals)
    "PoolAction",
    "ConfigAction",
    "ProxywhirlAction",
    "LogLevel",
    "CacheFormat",
    "Protocol",
    "ProxyProtocol",
    "ProxyType",
    "ValidationLevelType",
    "PerformanceLevel",
    # Type Aliases (Callbacks)
    "HttpRequestCallback",
    "AsyncHttpRequestCallback",
    "CacheEvictionCallback",
    "ProxyAddCallback",
    "ProxyRemoveCallback",
    "ProxySelectionCallback",
    "HealthCheckCallback",
    "SessionCallback",
    "SessionEvictionCallback",
    "RetryCallback",
    "ErrorHandlerCallback",
    "MetricsCallback",
    "LoggingCallback",
    "MCPMiddlewareCallback",
    # Built-in Proxy Sources (Individual)
    "GEONODE_HTTP",
    "GEONODE_SOCKS4",
    "GEONODE_SOCKS5",
    "GITHUB_THESPEEDX_HTTP",
    "GITHUB_THESPEEDX_SOCKS4",
    "GITHUB_THESPEEDX_SOCKS5",
    "GITHUB_MONOSANS_HTTP",
    "GITHUB_MONOSANS_SOCKS4",
    "GITHUB_MONOSANS_SOCKS5",
    "GITHUB_PROXIFLY_HTTP",
    "GITHUB_PROXIFLY_SOCKS4",
    "GITHUB_PROXIFLY_SOCKS5",
    "GITHUB_KOMUTAN_HTTP",
    "GITHUB_KOMUTAN_SOCKS4",
    "GITHUB_KOMUTAN_SOCKS5",
    # Built-in Proxy Sources (Collections)
    "ALL_HTTP_SOURCES",
    "ALL_SOCKS4_SOURCES",
    "ALL_SOCKS5_SOURCES",
    "ALL_SOURCES",
    "RECOMMENDED_SOURCES",
    "API_SOURCES",
]
