"""ProxyWhirl: Python proxy rotation with fetching, validation, and persistence."""

from __future__ import annotations

from importlib.metadata import PackageNotFoundError, version

from proxywhirl.browser import BrowserRenderer
from proxywhirl.cache import CacheConfig, CacheManager
from proxywhirl.circuit_breaker import AsyncCircuitBreaker, CircuitBreaker, CircuitBreakerState
from proxywhirl.config import DataStorageConfig
from proxywhirl.exceptions import (
    BrowserRenderError,
    CacheCorruptionError,
    CacheStorageError,
    CacheValidationError,
    CircuitBreakerOpenError,
    EventLoopConflictError,
    ProxyAuthenticationError,
    ProxyConnectionError,
    ProxyErrorCode,
    ProxyFetchError,
    ProxyPoolEmptyError,
    ProxySourceUnavailableError,
    ProxyStorageError,
    ProxyValidationError,
    ProxyWhirlError,
    RateLimitExceededError,
    RequestQueueFullError,
    redact_url,
)
from proxywhirl.fetchers import (
    CSVParser,
    HTMLTableParser,
    JSONParser,
    PlainTextParser,
    ProxyFetcher,
    ProxyValidator,
    ValidationResult,
    deduplicate_proxies,
)
from proxywhirl.models import (
    BootstrapConfig,
    CircuitBreakerConfig,
    HealthMonitor,
    HealthStatus,
    PoolSummary,
    Proxy,
    ProxyChain,
    ProxyCredentials,
    ProxyFormat,
    ProxyPool,
    ProxySource,
    ProxySourceConfig,
    ProxyStatus,
    RenderMode,
    RequestResult,
    SelectionContext,
    Session,
    SourceStats,
    StorageBackend,
    StrategyConfig,
    ValidationLevel,
)
from proxywhirl.rate_limiting import AsyncRateLimiter, RateLimit, RateLimiter, RateLimitEvent
from proxywhirl.retry import (
    BackoffStrategy,
    NonRetryableError,
    RetryableError,
    RetryExecutor,
    RetryMetrics,
    RetryPolicy,
)
from proxywhirl.rotator import AsyncProxyWhirl, ProxyWhirl
from proxywhirl.safe_regex import (
    RegexComplexityError,
    RegexTimeoutError,
    safe_regex_compile,
    safe_regex_findall,
    safe_regex_match,
    safe_regex_search,
    validate_regex_pattern,
)
from proxywhirl.settings import ProxyConfiguration
from proxywhirl.sources import (
    ALL_HTTP_SOURCES,
    ALL_SOCKS4_SOURCES,
    ALL_SOCKS5_SOURCES,
    ALL_SOURCES,
    API_SOURCES,
    RECOMMENDED_SOURCES,
    validate_sources,
    validate_sources_sync,
)
from proxywhirl.storage import FileStorage, SQLiteStorage
from proxywhirl.strategies import (
    CompositeStrategy,
    CostAwareStrategy,
    GeoTargetedStrategy,
    LeastUsedStrategy,
    PerformanceBasedStrategy,
    ProxyMetrics,
    RandomStrategy,
    RotationStrategy,
    RoundRobinStrategy,
    SessionManager,
    SessionPersistenceStrategy,
    StrategyRegistry,
    StrategyState,
    WeightedStrategy,
)
from proxywhirl.utils import (
    configure_logging,
    create_proxy_from_url,
    decrypt_credentials,
    encrypt_credentials,
    generate_encryption_key,
    is_valid_proxy_url,
    mask_proxy_url,
    mask_secret_str,
    parse_proxy_url,
    proxy_to_dict,
    public_proxy_url,
    scrub_credentials_from_dict,
    validate_proxy_model,
    validate_target_url_safe,
)

try:
    __version__ = version("proxywhirl")
except PackageNotFoundError:  # pragma: no cover - editable source tree fallback
    __version__ = "0.0.0"


__all__ = [
    "ALL_HTTP_SOURCES",
    "ALL_SOCKS4_SOURCES",
    "ALL_SOCKS5_SOURCES",
    "ALL_SOURCES",
    "API_SOURCES",
    "AsyncCircuitBreaker",
    "AsyncProxyWhirl",
    "AsyncRateLimiter",
    "BackoffStrategy",
    "BootstrapConfig",
    "BrowserRenderError",
    "BrowserRenderer",
    "CSVParser",
    "CacheConfig",
    "CacheCorruptionError",
    "CacheManager",
    "CacheStorageError",
    "CacheValidationError",
    "CircuitBreaker",
    "CircuitBreakerConfig",
    "CircuitBreakerOpenError",
    "CircuitBreakerState",
    "CompositeStrategy",
    "CostAwareStrategy",
    "DataStorageConfig",
    "EventLoopConflictError",
    "FileStorage",
    "GeoTargetedStrategy",
    "HTMLTableParser",
    "HealthMonitor",
    "HealthStatus",
    "JSONParser",
    "LeastUsedStrategy",
    "NonRetryableError",
    "PerformanceBasedStrategy",
    "PlainTextParser",
    "PoolSummary",
    "Proxy",
    "ProxyAuthenticationError",
    "ProxyChain",
    "ProxyConfiguration",
    "ProxyConnectionError",
    "ProxyCredentials",
    "ProxyErrorCode",
    "ProxyFetcher",
    "ProxyFetchError",
    "ProxyFormat",
    "ProxyMetrics",
    "ProxyPool",
    "ProxyPoolEmptyError",
    "ProxySource",
    "ProxySourceConfig",
    "ProxySourceUnavailableError",
    "ProxyStatus",
    "ProxyStorageError",
    "ProxyValidationError",
    "ProxyValidator",
    "ProxyWhirl",
    "ProxyWhirlError",
    "RECOMMENDED_SOURCES",
    "RandomStrategy",
    "RateLimit",
    "RateLimitEvent",
    "RateLimitExceededError",
    "RateLimiter",
    "RegexComplexityError",
    "RegexTimeoutError",
    "RenderMode",
    "RequestQueueFullError",
    "RequestResult",
    "RetryExecutor",
    "RetryMetrics",
    "RetryPolicy",
    "RetryableError",
    "RotationStrategy",
    "RoundRobinStrategy",
    "SQLiteStorage",
    "SelectionContext",
    "Session",
    "SessionManager",
    "SessionPersistenceStrategy",
    "SourceStats",
    "StorageBackend",
    "StrategyConfig",
    "StrategyRegistry",
    "StrategyState",
    "ValidationLevel",
    "ValidationResult",
    "WeightedStrategy",
    "__version__",
    "configure_logging",
    "create_proxy_from_url",
    "deduplicate_proxies",
    "decrypt_credentials",
    "encrypt_credentials",
    "generate_encryption_key",
    "is_valid_proxy_url",
    "mask_proxy_url",
    "mask_secret_str",
    "parse_proxy_url",
    "proxy_to_dict",
    "public_proxy_url",
    "redact_url",
    "safe_regex_compile",
    "safe_regex_findall",
    "safe_regex_match",
    "safe_regex_search",
    "scrub_credentials_from_dict",
    "validate_proxy_model",
    "validate_regex_pattern",
    "validate_sources",
    "validate_sources_sync",
    "validate_target_url_safe",
]
