"""Global constants for ProxyWhirl configuration and defaults."""

from __future__ import annotations

# Connection and timeout defaults (seconds)
DEFAULT_TIMEOUT = 10
DEFAULT_CONNECT_TIMEOUT = 5
DEFAULT_READ_TIMEOUT = 10
DEFAULT_POOL_TIMEOUT = 30

# Retry and resilience configuration
MAX_RETRIES = 3
INITIAL_RETRY_DELAY = 1
MAX_RETRY_DELAY = 60
RETRY_BACKOFF_FACTOR = 2

# Pool sizing and management
DEFAULT_POOL_SIZE = 100
MAX_POOL_SIZE = 10000
MIN_POOL_SIZE = 5

# Cache configuration (seconds and bytes)
DEFAULT_CACHE_TTL = 3600  # 1 hour
MIN_CACHE_TTL = 60  # 1 minute
MAX_CACHE_TTL = 86400  # 24 hours
DEFAULT_CACHE_MAX_SIZE = 100 * 1024 * 1024  # 100 MB
CACHE_CLEANUP_INTERVAL = 300  # 5 minutes

# Rate limiting and circuit breaker
RATE_LIMIT_REQUESTS_PER_MINUTE = 1000
CIRCUIT_BREAKER_FAILURE_THRESHOLD = 5
CIRCUIT_BREAKER_RECOVERY_TIMEOUT = 60
CIRCUIT_BREAKER_HALF_OPEN_REQUESTS = 1

# Health check configuration
HEALTH_CHECK_INTERVAL = 300  # 5 minutes
HEALTH_CHECK_TIMEOUT = 5
MAX_CONSECUTIVE_FAILURES = 3
HEALTH_CHECK_SUCCESS_THRESHOLD = 0.8

# Session and connection pooling
DEFAULT_SESSION_TTL = 3600
DEFAULT_SESSION_POOL_SIZE = 100
SESSION_REUSE_PROBABILITY = 0.8

# Quota and resource management
DEFAULT_QUOTA_REQUESTS_PER_MINUTE = 1000
DEFAULT_QUOTA_BANDWIDTH_MB_PER_HOUR = 100
DEFAULT_QUOTA_CONCURRENT_SESSIONS = 100

# Database and storage
DEFAULT_DB_TIMEOUT = 30
DB_POOL_SIZE = 5
DB_MAX_OVERFLOW = 10
DB_STATEMENT_CACHE_SIZE = 100

# Logging and metrics
LOG_LEVEL_DEFAULT = "INFO"
METRICS_COLLECTION_INTERVAL = 60
METRICS_RETENTION_DAYS = 30

# Search and indexing
SEARCH_RESULT_LIMIT = 1000
SEARCH_TIMEOUT = 5
FTS_MIN_TERM_LENGTH = 2

# Browser and JavaScript rendering
BROWSER_TIMEOUT = 30
BROWSER_HEADLESS_MODE = True
BROWSER_POOL_SIZE = 5

# Batch operations
BATCH_SIZE_DEFAULT = 100
BATCH_TIMEOUT = 300

# String and regex patterns
PROXY_URL_PATTERN_TIMEOUT = 5  # seconds for regex matching
REGEX_COMPLEXITY_LIMIT = 1000
REGEX_MAX_BACKTRACK = 10000

# File operations
MAX_FILE_SIZE = 50 * 1024 * 1024  # 50 MB
MAX_LOG_FILE_SIZE = 100 * 1024 * 1024  # 100 MB
MAX_LOG_FILES_TO_KEEP = 10

# API and web service
API_REQUEST_TIMEOUT = 30
API_MAX_RETRIES = 3
WEB_SOCKET_TIMEOUT = 60

# Telemetry and sampling
DEFAULT_TRACE_SAMPLE_RATE = 0.1  # 10% of traces
MIN_TRACE_SAMPLE_RATE = 0.01
MAX_TRACE_SAMPLE_RATE = 1.0

# Gradual rollout configuration
ROLLOUT_INCREMENT_PERCENTAGE = 10  # 10% per step
ROLLOUT_MONITORING_WINDOW = 300  # 5 minutes
ROLLOUT_ERROR_THRESHOLD = 0.05  # 5% error rate

# Source discovery
SOURCE_DISCOVERY_INTERVAL = 86400  # 24 hours
SOURCE_DISCOVERY_TIMEOUT = 60
SOURCE_DISCOVERY_MAX_RETRIES = 3

# Performance thresholds
SLOW_REQUEST_THRESHOLD_MS = 5000
P50_LATENCY_TARGET_MS = 100
P95_LATENCY_TARGET_MS = 500
P99_LATENCY_TARGET_MS = 2000

# Data retention
DEFAULT_RETENTION_DAYS = 30
MIN_RETENTION_DAYS = 1
MAX_RETENTION_DAYS = 365

# Dual-write migration
DUAL_WRITE_VERIFICATION_INTERVAL = 3600  # 1 hour
DUAL_WRITE_MAX_VERIFICATION_ERRORS = 100
