"""add_analytics_tables

Revision ID: 616bc0c6a5b5
Revises: 58c0fadfa0ca
Create Date: 2025-11-21 00:38:11.416684+00:00

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = "616bc0c6a5b5"
down_revision: Union[str, None] = "58c0fadfa0ca"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade database schema.

    This migration applies forward schema changes. Always test migrations
    in a development environment before applying to production.
    """
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "daily_stats",
        sa.Column("date", sa.Date(), nullable=False),
        sa.Column("total_requests", sa.Integer(), nullable=False),
        sa.Column("total_successes", sa.Integer(), nullable=False),
        sa.Column("total_failures", sa.Integer(), nullable=False),
        sa.Column("avg_response_time_ms", sa.Float(), nullable=False),
        sa.PrimaryKeyConstraint("date"),
    )
    op.create_table(
        "request_logs",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("timestamp", sa.DateTime(), nullable=False),
        sa.Column("proxy_url", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("target_url", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("response_time_ms", sa.Float(), nullable=False),
        sa.Column("status_code", sa.Integer(), nullable=True),
        sa.Column("success", sa.Boolean(), nullable=False),
        sa.Column("error", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("request_logs", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_request_logs_proxy_url"), ["proxy_url"], unique=False)
        batch_op.create_index(batch_op.f("ix_request_logs_timestamp"), ["timestamp"], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade database schema.

    This migration reverts schema changes. Use with caution in production.
    Ensure data backups exist before running downgrades.
    """
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("request_logs", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_request_logs_timestamp"))
        batch_op.drop_index(batch_op.f("ix_request_logs_proxy_url"))

    op.drop_table("request_logs")
    op.drop_table("daily_stats")
    # ### end Alembic commands ###
