"""initial_schema

Revision ID: 58c0fadfa0ca
Revises:
Create Date: 2025-11-20 11:06:15.420696+00:00

"""

from typing import Sequence, Union

import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from alembic import op


# revision identifiers, used by Alembic.
revision: str = "58c0fadfa0ca"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade database schema.

    This migration applies forward schema changes. Always test migrations
    in a development environment before applying to production.
    """
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "cache_entries",
        sa.Column("key", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("proxy_url", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("username_encrypted", sa.LargeBinary(), nullable=True),
        sa.Column("password_encrypted", sa.LargeBinary(), nullable=True),
        sa.Column("source", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("fetch_time", sa.Float(), nullable=False),
        sa.Column("last_accessed", sa.Float(), nullable=False),
        sa.Column("access_count", sa.Integer(), nullable=False),
        sa.Column("ttl_seconds", sa.Integer(), nullable=False),
        sa.Column("expires_at", sa.Float(), nullable=False),
        sa.Column("health_status", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("failure_count", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.Float(), nullable=False),
        sa.Column("updated_at", sa.Float(), nullable=False),
        sa.PrimaryKeyConstraint("key"),
    )
    with op.batch_alter_table("cache_entries", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_cache_entries_expires_at"), ["expires_at"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_cache_entries_health_status"), ["health_status"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_cache_entries_last_accessed"), ["last_accessed"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_cache_entries_source"), ["source"], unique=False)

    op.create_table(
        "proxies",
        sa.Column("url", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("protocol", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("username", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("password", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("health_status", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("last_success_at", sa.DateTime(), nullable=True),
        sa.Column("last_failure_at", sa.DateTime(), nullable=True),
        sa.Column("total_requests", sa.Integer(), nullable=False),
        sa.Column("total_successes", sa.Integer(), nullable=False),
        sa.Column("total_failures", sa.Integer(), nullable=False),
        sa.Column("average_response_time_ms", sa.Float(), nullable=True),
        sa.Column("consecutive_failures", sa.Integer(), nullable=False),
        sa.Column("source", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("source_url", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("metadata_json", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("url"),
    )
    with op.batch_alter_table("proxies", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_proxies_source"), ["source"], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade database schema.

    This migration reverts schema changes. Use with caution in production.
    Ensure data backups exist before running downgrades.
    """
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("proxies", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_proxies_source"))

    op.drop_table("proxies")
    with op.batch_alter_table("cache_entries", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_cache_entries_source"))
        batch_op.drop_index(batch_op.f("ix_cache_entries_last_accessed"))
        batch_op.drop_index(batch_op.f("ix_cache_entries_health_status"))
        batch_op.drop_index(batch_op.f("ix_cache_entries_expires_at"))

    op.drop_table("cache_entries")
    # ### end Alembic commands ###
